### ISSUE TITLE
leak thông tin đăng nhập trang tuyển dụng (Issue #1)

### ISSUE THREAD

**Issue by linhdaonhat** [Nguyen-Trung-Kien/Nguyen-Trung-Kien#1]
Hê lô bác, 
Rất cảm ơn bác vì thông tin này.
Tui là nhân viên của cty TKS Vietnam bác ạ. Đang tập tành chút auto test và cả github 🙂))
Đã đưa code về private rồi nhaaa
Arigato ^^

---------------------------
Dao Nhat Linh (Ms)

TECH KNOWLEDGE SOLUTION VIETNAM CO., LTD
Addr: 5th Floor, 50/100 Dich Vong Hau, Cau Giay, Hanoi, Vietnam
Tel: +84 344 879 929
Email: linhdn@[tksvietnam.com](http://tksvietnam.com/)

**Comment by Nguyen-Trung-Kien** [comment]
tập tành vậy cũng căng bác ạ 😄

**Comment by Nguyen-Trung-Kien** [comment]
có gì thắc mắc hay cần hỏi thì hỏi nhé 😄 cần tips săn trên github thì nt hỏi luôn nè 😄 , đóng nhé
